### ISSUE TITLE
test_acessibilidade não está sendo executado

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#282]
[test_acessibilidade](https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/tests/robot/test_acessibilidade.robot) não está sendo executado:

```bash
bin/test -t test_acessibilidade
Total: 0 tests, 0 failures, 0 errors in 0.000 seconds.
```

**Comment by idgserpro** [comment]
O teste não está sendo executado porque [está literalmente comentado](https://github.com/plonegovbr/brasil.gov.portal/commit/7913be1ab313a148edea2d4403c646a74ee6b1aa), e fizeram isso porque dava problema com a barra.

[Criando uma branch](https://github.com/plonegovbr/brasil.gov.portal/tree/issue_282) para voltar a executar esses testes via [integração contínua](https://travis-ci.org/plonegovbr/brasil.gov.portal/jobs/242827790) não acontece mais o erro da barra, mas acontecem outros dois erros:

```
Failure in test Validar contraste de elementos (test_acessibilidade.robot)
Traceback (most recent call last):
  File "/home/travis/build/plonegovbr/brasil.gov.portal/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/plonegovbr/brasil.gov.portal/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in 1;36mrunTest
    assert last_status == 'PASS', last_message
AssertionError: Several failures occurred:
1) Contraste incorreto para o seletor #link-conteudo, valor obtido: 1.00, valor esperado: 4.50
2) Contraste incorreto para o seletor #link-navegacao, valor obtido: 1.00, valor esperado: 4.50
3) Contraste incorreto para o seletor #link-buscar, valor obtido: 1.00, valor esperado: 4.50
4) Contraste incorreto para o seletor #link-rodape, valor obtido: 1.00, valor esperado: 4.50
```

e

```
Failure in test Accesskeys (test_acessibilidade.robot)
Traceback (most recent call last):
  File "/home/travis/build/plonegovbr/brasil.gov.portal/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/plonegovbr/brasil.gov.portal/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
    assert last_status == 'PASS', last_message
AssertionError: ValueError: Element locator 'Ir para a navega\xe7\xe3o' did not match any elements.
```

O primeiro precisa ser estudado melhor inclusive pra ver se não é um erro nas diretrizes em http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/guia-de-estilo-identidade-padrao-comunicacao-digital-fev2015.pdf, já o segundo basta mudar o teste ao invés de "Ir para a navegação" colocar "Ir para o menu" (pois isso foi alterado em [commits anteriores](https://github.com/plonegovbr/brasil.gov.temas/commit/e69cb41e355037a3fd918bf1df4198c35b82409c) mas o teste não foi atualizado).
