### ISSUE TITLE
Ao atualizar para release 1.1.4 do IDG, na capa recebo o erro "error while rendering plone.app.iterate.baseline_info" ou "error while rendering plone.app.iterate.checkout_info"

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#310]
Ao atualizar uma instância IDG da versão 1.0.5, que possuía no ZODB uma cópia de iteração ativa da capa, para a versão 1.1.4 do IDG, esse erro passa a aparecer.

Traceback:

```
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.app.viewletmanager-2.0.5-py2.7.egg/plone/app/viewletmanager/manager.py", line 105, in render
    html.append(viewlet.render())
  File "/home/user/.buildout/eggs/plone.app.iterate-2.1.12-py2.7.egg/plone/app/iterate/browser/info.py", line 98, in render
    working_copy = self.working_copy()
  File "/home/user/.buildout/eggs/plone.memoize-1.1.1-py2.7.egg/plone/memoize/instance.py", line 51, in memogetter
    val=func(*args, **kwargs)
  File "/home/user/.buildout/eggs/plone.app.iterate-2.1.12-py2.7.egg/plone/app/iterate/browser/info.py", line 109, in working_copy
    refs = self.context.getBRefs( WorkingCopyRelation.relationship )
AttributeError: getBRefs
```

Por que isso acontece? Esse erro nasceu com a remoção do behavior plone.app.stagingbehavior.interfaces.IStagingSupport de collective.cover em

https://github.com/collective/collective.cover/commit/651cf0b86b45f9398dabc108a14d5c49f79367bf

e

https://github.com/collective/collective.cover/commit/3c5b9da7ca9330414f30400e54cbe432e2175834

obrigando os usuários que usam Plone 4 a adicionar, explicitamente, o plone.app.stagingbehavior como dependência e o behavior em algum lugar no xml do policy: é importante colocar o behavior também no xml do policy porque os behaviors de collective.cover no profile não possuem `purge=false` e portanto ao atualizar o cover ele irá remover esse behavior do seu portal (ver o relato https://github.com/collective/collective.cover/issues/638 para entender porque isso acontece e o andamento da adição do purge evitando esse erro no futuro).

Não temos essa lógica de adicionar o behavior explicitamente no IDG, portanto, o adicionaremos em https://github.com/plonegovbr/brasil.gov.tiles/issues/160.

Enquanto nada disso é feito, para corrigir esse erro você tem as opções:
- Ir no painel de controle, ir em "Tipos dexterity", "Comportamentos" e clicar "Staging", reativando o behavior que foi removido em Plone 4 que atualizou o cover;
- Atualizar a versão de plone.app.iterate para 2.1.17 (correção do erro foi efetuada em https://github.com/plone/plone.app.iterate/commit/9f333f08cf31b4b1f8bb8cda31536325ba128e15);
- Reinstalar, no "portal_setup", os upgrades de plone.app.iterate. Não testamos essa 3a opção e nem fomos a fundo entender porque fazendo isso funciona, portanto, recomendamos apenas a primeira opção.

No Plone 4.3.10, a versão do plone.app.iterate é atualizada, portanto fica esse relato aberto para:
- Pessoas que tenham esse erro, ao pesquisar no google, encontrem essa solução;
- Lembrete para atualizarmos o Plone para 4.3.10 num futuro próximo.

**Comment by idgserpro** [comment]
Corrigido em https://github.com/plonegovbr/brasil.gov.portal/issues/331.
