### ISSUE TITLE
Corrigir erros das visões de coleção

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#359]
Corrigir erro das visões:

- [x] [collection_summary_view](https://github.com/plonegovbr/brasil.gov.portal/blob/9cb7649751e4843ac56f1fdbc8081f8de45ecd9b/src/brasil/gov/portal/tests/test_esconde_autor_data.py#L134)

```
Failure in test test_collection_summary_view (brasil.gov.portal.tests.test_esconde_autor_data.EscondeAutorDataFunctionalTestCase)
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/plonegovbr/brasil.gov.portal/src/brasil/gov/portal/tests/test_esconde_autor_data.py", line 134, in test_collection_summary_view
    self.base_teste_esconde_autor_data('summary_view', obj)
  File "/home/travis/build/plonegovbr/brasil.gov.portal/src/brasil/gov/portal/tests/test_esconde_autor_data.py", line 113, in base_teste_esconde_autor_data
    self.assertIn('Pagina', contents)
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 803, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: 'Pagina' not found in '<!DOCTYPE html>\n<html lang="pt-br" dir="ltr"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><base href="http://nohost/plone/objeto"><!--[if lt IE 7]></base><![endif]--><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/reset-cachekey-169c3cd9ea913e6c4d1394e77063050d.css" media="screen"><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/base-cachekey-31168804aa1a1ab47f698ea31b86a5f8.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourceplone.app.jquerytools.dateinput-cachekey-933e6c12796046db3f705f22e933c9e7.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourceplone.formwidget.datetimestyles-cachekey-c617112e3d0985a5246d929a181465db.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecalendar_stylescalendar-cachekey-61a5e6ef146c5e409496a0b3c38f99cd.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourcebrasil.gov.agendaagenda-cachekey-eb265b9559830005089865fda6d0fe22.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.nitfnitf-cachekey-3d5cd0c0ce416e4d96c93e5dd6648d44.css);</style><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.pollscsscollective.polls-cachekey-aaed76c89297ab8d4d26806212654c52.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/ploneCustom-cachekey-a64a075104aea8a90a6870672b8fabf2.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/jquery.autocomplete-cachekey-a24eb8b3e71b7c70549d1492c47a0895.css);</style><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourceProducts.Doormat.stylesheetsdoormat-cachekey-21408a9a3c0870116a0ff6dbe258946f.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/embedder-cachekey-1735c763d30be804baef48c526b8200d.css" media="screen"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.uploadcssbootstrap.min-cachekey-969f7c57412471305db1aaa6c71ba0b2.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourcebrasil.gov.portalcssmain-cachekey-f3d50b2fb1f3bbca594159aa1ed005a9.css"><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourceplone.app.jquery-cachekey-f24881ebd11641f45b596ddac2a05773.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/register_function-cachekey-683b9103204022e706aa5fe29c07257f.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourceplone.formwidget.recurrencejquery.tmpl-beta1-cachekey-64b7ecda4b030ae1c73f1457d10331a8.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.js.bootstrapjsbootstrap.min-cachekey-303f1f6008dffeabae1fdbef568f2489.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.coverjsmain-cachekey-5e17b50f967946bb98dd5be259caee04.js"></script><!--[if lte IE 8]>\n     \n    <script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.pollsjsexcanvas.min-cachekey-98f11ce404ffa4442aaafb5b8216be4a.js"></script>\n       <![endif]--><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.pollsjspolls-cachekey-00f969fe225bcd3b358b669d4715b1da.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcejquery.cookie-cachekey-1842b0bacc983ee2a6ef47e2551a6732.js"></script><title>Cole\xc3\xa7\xc3\xa3o \xe2\x80\x94 Secretaria de Comunica\xc3\xa7\xc3\xa3o Social</title><link rel="http://purl.org/dc/terms/subject http://schema.org/about http://xmlns.com/foaf/0.1/primaryTopic" href="http://vocab.e.gov.br/2011/03/vcge#esquema"><link rel="author" href="http://nohost/plone/author/test_user_1_" title="Informa\xc3\xa7\xc3\xb5es do Autor"><link rel="canonical" href="http://nohost/plone/objeto"><script type="text/javascript">\n        jQuery(function($){\n            if (typeof($.datepicker) != "undefined"){\n              $.datepicker.setDefaults(\n                jQuery.extend($.datepicker.regional[\'pt-BR\'],\n                {dateFormat: \'dd/mm/yy\'}));\n            }\n        });\n        </script><link rel="search" href="http://nohost/plone/@@search" title="Buscar neste site"><meta name="generator" content="Plone - http://plone.org"><meta content="width=device-width, initial-scale=1.0" name="viewport"><link rel="shortcut icon" href="/plone/++theme++verde/img/favicon.ico" type="image/x-icon"><link rel="apple-touch-icon" href="/plone/++theme++verde/img/touch_icon.png"><!-- Plone CSS - only for preview, will be removed in rules.xml --><!-- Theme CSS - only for preview, will be removed in rules and added in CSS registry --><link media="all" href="/plone/++theme++verde/css/style.css" type="text/css" rel="stylesheet"></head><body dir="ltr" class="template-summary_view portaltype-collection site-plone section-objeto userrole-anonymous"><div id="accessibility-wrapper">\n            <ul id="accessibility"><li>\n                        <a accesskey="1" href="#acontent" id="link-conteudo">Ir para o conte\xc3\xbado <span>1</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="2" href="#anavigation" id="link-navegacao">Ir para o menu <span>2</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="3" href="#SearchableText" id="link-buscar">Ir para a busca <span>3</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="4" href="#afooter" id="link-rodape">Ir para o rodap\xc3\xa9 <span>4</span></a>\n                    </li>\n                </ul><ul id="portal-siteactions"><li id="siteaction-accessibility"><a href="http://nohost/plone/acessibilidade" title="Acessibilidade" accesskey="5">Acessibilidade</a></li>\n    <li id="siteaction-contraste"><a href="#" title="Alto Contraste" accesskey="6">Alto Contraste</a></li>\n    <li id="siteaction-mapadosite"><a href="http://nohost/plone/mapadosite" title="Mapa do Site" accesskey="7">Mapa do Site</a></li>\n</ul></div><div id="barra-identidade">\n    <div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">\n            <ul id="menu-barra-temp" style="list-style:none;"><li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>\n                    <li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>\n            </ul></div>\n</div><div id="wrapper">\n\n        <!-- HEADER -->\n\n        <div id="header" role="banner">\n\n            <div>\n            <div id="logo">\n    <a id="portal-logo" title="O portal do Brasil" href="http://nohost/plone">\n            <span id="portal-title-1">Secretaria de</span>\n            <h1 id="portal-title" class="corto">Comunica\xc3\xa7\xc3\xa3o Social</h1>\n            <span id="portal-description">Presid\xc3\xaancia da Rep\xc3\xbablica</span>\n    </a>\n</div>\n\n            <div id="portal-searchbox">\n\n    <form id="nolivesearchGadget_form" action="http://nohost/plone/@@busca">\n        <fieldset class="LSBox"><legend class="hiddenStructure">Buscar no portal</legend>\n            <label class="hiddenStructure" for="nolivesearchGadget">Buscar no portal</label>\n\n            <input name="SearchableText" type="text" size="18" title="Buscar no portal" placeholder="Buscar no portal" class="searchField" id="nolivesearchGadget"><input class="searchButton" type="submit" value="Buscar no portal"></fieldset></form>\n\n</div>\n\n            <div id="social-icons">\n                <ul><li id="portalredes-twitter" class="portalredes-item">\n                <a href="https://twitter.com/twitter">Twitter</a>\n            </li><li id="portalredes-youtube" class="portalredes-item">\n                <a href="http://youtube.com/youtube">YouTube</a>\n            </li><li id="portalredes-facebook" class="portalredes-item">\n                <a href="http://facebook.com/facebook">Facebook</a>\n            </li><li id="portalredes-flickr" class="portalredes-item">\n                <a href="http://flickr.com/flickr">Flickr</a>\n            </li></ul></div>\n\n        </div>\n        <div id="sobre">\n            <ul></ul></div>\n    </div>\n\n    <!-- content -->\n\n    <div id="main" role="main">\n    <div id="plone-content">\n\n        <!-- Demo Plone Content -->\n\n        <div id="portal-columns" class="row">\n\n            <div id="viewlet-above-content"><div id="portal-breadcrumbs">\n    <span id="breadcrumbs-you-are-here">Voc\xc3\xaa est\xc3\xa1 aqui:</span>\n    <span id="breadcrumbs-home">\n        <a href="http://nohost/plone">P\xc3\xa1gina Inicial</a>\n        <span class="breadcrumbSeparator">\n            &gt;\n            \n        </span>\n    </span>\n    <span dir="ltr" id="breadcrumbs-1">\n        \n            \n            \n            <span id="breadcrumbs-current">Cole\xc3\xa7\xc3\xa3o</span>\n         \n    </span>\n\n</div>\n</div>\n\n            <!-- Column 1 -->\n            <div id="navigation">\n                <a name="anavigation" id="anavigation"></a>\n                <span class="menuTrigger">Menu</span>\n                </div>\n\n            <!-- Conteudo -->\n            <div id="portal-column-content" class="cell width-full position-0">\n                <a name="acontent" id="acontent"></a>\n\n                <div class="">\n\n                    \n\n                    \n\n    <dl class="portalMessage info" id="kssPortalMessage" style="display:none"><dt>Info</dt>\n        <dd></dd>\n    </dl><div id="content">\n\n                            \n\n                            \n\n                             <div id="viewlet-above-content-title"></div>\n                             \n                                 \n                                 \n            \n            <h1 class="documentFirstHeading">Cole\xc3\xa7\xc3\xa3o</h1>\n        \n                             \n                             <div id="viewlet-below-content-title">\n\n<div class="documentByLine" id="plone-document-byline">\n  \n\n  \n\n  \n\n  \n\n  \n\n  \n\n  \n\n</div>\n</div>\n\n                             \n                                 \n                                 \n            \n            \n        \n                             \n\n                             <div id="viewlet-above-content-body"></div>\n                             <div id="content-core">\n                                 \n            \n\n    \n\n    \n    \n    \n    \n        <p class="discreet">There are currently no items in this folder.</p>\n    \n\n    \n    \n\n\n        \n                             </div>\n                             \n\n                            \n                        </div>\n                    \n\n                    \n                </div>\n\n                <div id="viewlet-below-content">\n\n\n</div>\n\n            </div>\n\n            <!-- Column 2-->\n\n            \n\n        </div>\n\n        <!-- /Demo Plone Content -->\n\n    </div>\n\n    <div class="clear"></div>\n    <div id="voltar-topo">\n    <a href="#wrapper">Voltar para o topo</a>\n</div>\n\n</div>\n\n<!-- Footer -->\n<div id="footer" role="contentinfo">\n    <a name="afooter" id="afooter"></a>\n\n    <div id="doormat-container" class="columns-1">\n\n  <h2>Doormat</h2>\n  <div class="doormatColumn column-0">\n    <h3>Section 1</h3>\n    <dl class="doormatSection"><dt class="doormatSectionHeader">Section 1</dt>\n      <dd class="doormatSectionBody">\n        \n        <p>\nThis is the default doormat text.\nPlease go to /doormat/column-1/section-1/document-1/edit to edit it.\n</p>\n      </dd>\n    </dl></div>\n</div>\n    <div class="clear"></div>\n    <div id="footer-brasil" class="footer-logos"></div>\n</div>\n<div id="extra-footer">\n    <p>Desenvolvido com o CMS de c\xc3\xb3digo aberto <a href="http://plone.org">Plone</a></p>\n</div>\n\n<!-- /Footer-->\n\n    \n    \n    <script defer src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>\n</div></body></html>\n'
```

- [x] [collection_listing_view](https://github.com/plonegovbr/brasil.gov.portal/blob/9cb7649751e4843ac56f1fdbc8081f8de45ecd9b/src/brasil/gov/portal/tests/test_esconde_autor_data.py#L162)

```
Failure in test test_collection_listing_view (brasil.gov.portal.tests.test_esconde_autor_data.EscondeAutorDataFunctionalTestCase)
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/plonegovbr/brasil.gov.portal/src/brasil/gov/portal/tests/test_esconde_autor_data.py", line 158, in test_collection_listing_view
    self.base_teste_esconde_autor_data('listing_view', obj)
  File "/home/travis/build/plonegovbr/brasil.gov.portal/src/brasil/gov/portal/tests/test_esconde_autor_data.py", line 113, in base_teste_esconde_autor_data
    self.assertIn('Pagina', contents)
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 803, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/python/2.7.9/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: 'Pagina' not found in '<!DOCTYPE html>\n<html lang="pt-br" dir="ltr"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><base href="http://nohost/plone/objeto"><!--[if lt IE 7]></base><![endif]--><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/reset-cachekey-169c3cd9ea913e6c4d1394e77063050d.css" media="screen"><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/base-cachekey-31168804aa1a1ab47f698ea31b86a5f8.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourceplone.app.jquerytools.dateinput-cachekey-933e6c12796046db3f705f22e933c9e7.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourceplone.formwidget.datetimestyles-cachekey-c617112e3d0985a5246d929a181465db.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecalendar_stylescalendar-cachekey-61a5e6ef146c5e409496a0b3c38f99cd.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourcebrasil.gov.agendaagenda-cachekey-eb265b9559830005089865fda6d0fe22.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.nitfnitf-cachekey-3d5cd0c0ce416e4d96c93e5dd6648d44.css);</style><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.pollscsscollective.polls-cachekey-aaed76c89297ab8d4d26806212654c52.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/ploneCustom-cachekey-a64a075104aea8a90a6870672b8fabf2.css"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/jquery.autocomplete-cachekey-a24eb8b3e71b7c70549d1492c47a0895.css);</style><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourceProducts.Doormat.stylesheetsdoormat-cachekey-21408a9a3c0870116a0ff6dbe258946f.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/embedder-cachekey-1735c763d30be804baef48c526b8200d.css" media="screen"><style type="text/css" media="screen">@import url(http://nohost/plone/portal_css/Sunburst%20Theme/resourcecollective.uploadcssbootstrap.min-cachekey-969f7c57412471305db1aaa6c71ba0b2.css);</style><link rel="stylesheet" type="text/css" href="http://nohost/plone/portal_css/Sunburst%20Theme/resourcebrasil.gov.portalcssmain-cachekey-f3d50b2fb1f3bbca594159aa1ed005a9.css"><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourceplone.app.jquery-cachekey-f24881ebd11641f45b596ddac2a05773.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/register_function-cachekey-683b9103204022e706aa5fe29c07257f.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourceplone.formwidget.recurrencejquery.tmpl-beta1-cachekey-64b7ecda4b030ae1c73f1457d10331a8.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.js.bootstrapjsbootstrap.min-cachekey-303f1f6008dffeabae1fdbef568f2489.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.coverjsmain-cachekey-5e17b50f967946bb98dd5be259caee04.js"></script><!--[if lte IE 8]>\n     \n    <script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.pollsjsexcanvas.min-cachekey-98f11ce404ffa4442aaafb5b8216be4a.js"></script>\n       <![endif]--><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcecollective.pollsjspolls-cachekey-00f969fe225bcd3b358b669d4715b1da.js"></script><script type="text/javascript" src="http://nohost/plone/portal_javascripts/Sunburst%20Theme/resourcejquery.cookie-cachekey-1842b0bacc983ee2a6ef47e2551a6732.js"></script><title>Cole\xc3\xa7\xc3\xa3o \xe2\x80\x94 Secretaria de Comunica\xc3\xa7\xc3\xa3o Social</title><link rel="http://purl.org/dc/terms/subject http://schema.org/about http://xmlns.com/foaf/0.1/primaryTopic" href="http://vocab.e.gov.br/2011/03/vcge#esquema"><link rel="author" href="http://nohost/plone/author/test_user_1_" title="Informa\xc3\xa7\xc3\xb5es do Autor"><link rel="canonical" href="http://nohost/plone/objeto"><script type="text/javascript">\n        jQuery(function($){\n            if (typeof($.datepicker) != "undefined"){\n              $.datepicker.setDefaults(\n                jQuery.extend($.datepicker.regional[\'pt-BR\'],\n                {dateFormat: \'dd/mm/yy\'}));\n            }\n        });\n        </script><link rel="search" href="http://nohost/plone/@@search" title="Buscar neste site"><meta name="generator" content="Plone - http://plone.org"><meta content="width=device-width, initial-scale=1.0" name="viewport"><link rel="shortcut icon" href="/plone/++theme++verde/img/favicon.ico" type="image/x-icon"><link rel="apple-touch-icon" href="/plone/++theme++verde/img/touch_icon.png"><!-- Plone CSS - only for preview, will be removed in rules.xml --><!-- Theme CSS - only for preview, will be removed in rules and added in CSS registry --><link media="all" href="/plone/++theme++verde/css/style.css" type="text/css" rel="stylesheet"></head><body dir="ltr" class="template-listing_view portaltype-collection site-plone section-objeto userrole-anonymous"><div id="accessibility-wrapper">\n            <ul id="accessibility"><li>\n                        <a accesskey="1" href="#acontent" id="link-conteudo">Ir para o conte\xc3\xbado <span>1</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="2" href="#anavigation" id="link-navegacao">Ir para o menu <span>2</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="3" href="#SearchableText" id="link-buscar">Ir para a busca <span>3</span></a>\n                    </li>\n                    <li>\n                        <a accesskey="4" href="#afooter" id="link-rodape">Ir para o rodap\xc3\xa9 <span>4</span></a>\n                    </li>\n                </ul><ul id="portal-siteactions"><li id="siteaction-accessibility"><a href="http://nohost/plone/acessibilidade" title="Acessibilidade" accesskey="5">Acessibilidade</a></li>\n    <li id="siteaction-contraste"><a href="#" title="Alto Contraste" accesskey="6">Alto Contraste</a></li>\n    <li id="siteaction-mapadosite"><a href="http://nohost/plone/mapadosite" title="Mapa do Site" accesskey="7">Mapa do Site</a></li>\n</ul></div><div id="barra-identidade">\n    <div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">\n            <ul id="menu-barra-temp" style="list-style:none;"><li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>\n                    <li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>\n            </ul></div>\n</div><div id="wrapper">\n\n        <!-- HEADER -->\n\n        <div id="header" role="banner">\n\n            <div>\n            <div id="logo">\n    <a id="portal-logo" title="O portal do Brasil" href="http://nohost/plone">\n            <span id="portal-title-1">Secretaria de</span>\n            <h1 id="portal-title" class="corto">Comunica\xc3\xa7\xc3\xa3o Social</h1>\n            <span id="portal-description">Presid\xc3\xaancia da Rep\xc3\xbablica</span>\n    </a>\n</div>\n\n            <div id="portal-searchbox">\n\n    <form id="nolivesearchGadget_form" action="http://nohost/plone/@@busca">\n        <fieldset class="LSBox"><legend class="hiddenStructure">Buscar no portal</legend>\n            <label class="hiddenStructure" for="nolivesearchGadget">Buscar no portal</label>\n\n            <input name="SearchableText" type="text" size="18" title="Buscar no portal" placeholder="Buscar no portal" class="searchField" id="nolivesearchGadget"><input class="searchButton" type="submit" value="Buscar no portal"></fieldset></form>\n\n</div>\n\n            <div id="social-icons">\n                <ul><li id="portalredes-twitter" class="portalredes-item">\n                <a href="https://twitter.com/twitter">Twitter</a>\n            </li><li id="portalredes-youtube" class="portalredes-item">\n                <a href="http://youtube.com/youtube">YouTube</a>\n            </li><li id="portalredes-facebook" class="portalredes-item">\n                <a href="http://facebook.com/facebook">Facebook</a>\n            </li><li id="portalredes-flickr" class="portalredes-item">\n                <a href="http://flickr.com/flickr">Flickr</a>\n            </li></ul></div>\n\n        </div>\n        <div id="sobre">\n            <ul></ul></div>\n    </div>\n\n    <!-- content -->\n\n    <div id="main" role="main">\n    <div id="plone-content">\n\n        <!-- Demo Plone Content -->\n\n        <div id="portal-columns" class="row">\n\n            <div id="viewlet-above-content"><div id="portal-breadcrumbs">\n    <span id="breadcrumbs-you-are-here">Voc\xc3\xaa est\xc3\xa1 aqui:</span>\n    <span id="breadcrumbs-home">\n        <a href="http://nohost/plone">P\xc3\xa1gina Inicial</a>\n        <span class="breadcrumbSeparator">\n            &gt;\n            \n        </span>\n    </span>\n    <span dir="ltr" id="breadcrumbs-1">\n        \n            \n            \n            <span id="breadcrumbs-current">Cole\xc3\xa7\xc3\xa3o</span>\n         \n    </span>\n\n</div>\n</div>\n\n            <!-- Column 1 -->\n            <div id="navigation">\n                <a name="anavigation" id="anavigation"></a>\n                <span class="menuTrigger">Menu</span>\n                </div>\n\n            <!-- Conteudo -->\n            <div id="portal-column-content" class="cell width-full position-0">\n                <a name="acontent" id="acontent"></a>\n\n                <div class="">\n\n                    \n\n                    \n\n    <dl class="portalMessage info" id="kssPortalMessage" style="display:none"><dt>Info</dt>\n        <dd></dd>\n    </dl><div id="content">\n\n                            \n\n                            \n\n                             <div id="viewlet-above-content-title"></div>\n                             \n                                 \n                                 \n            \n            <h1 class="documentFirstHeading">Cole\xc3\xa7\xc3\xa3o</h1>\n        \n                             \n                             <div id="viewlet-below-content-title">\n\n<div class="documentByLine" id="plone-document-byline">\n  \n\n  \n\n  \n\n  \n\n  \n\n  \n\n  \n\n</div>\n</div>\n\n                             \n                                 \n                                 \n            \n            \n        \n                             \n\n                             <div id="viewlet-above-content-body"></div>\n                             <div id="content-core">\n                                 \n\n\n    \n\n    \n    \n    \n    \n        <p class="discreet">Atualmente n\xc3\xa3o existem itens nessa pasta.</p>\n    \n\n    \n    \n\n\n\n                             </div>\n                             \n\n                            \n                        </div>\n                    \n\n                    \n                </div>\n\n                <div id="viewlet-below-content">\n\n\n\n\n\n\n\n</div>\n\n            </div>\n\n            <!-- Column 2-->\n\n            \n\n        </div>\n\n        <!-- /Demo Plone Content -->\n\n    </div>\n\n    <div class="clear"></div>\n    <div id="voltar-topo">\n    <a href="#wrapper">Voltar para o topo</a>\n</div>\n\n</div>\n\n<!-- Footer -->\n<div id="footer" role="contentinfo">\n    <a name="afooter" id="afooter"></a>\n\n    <div id="doormat-container" class="columns-1">\n\n  <h2>Doormat</h2>\n  <div class="doormatColumn column-0">\n    <h3>Section 1</h3>\n    <dl class="doormatSection"><dt class="doormatSectionHeader">Section 1</dt>\n      <dd class="doormatSectionBody">\n        \n        <p>\nThis is the default doormat text.\nPlease go to /doormat/column-1/section-1/document-1/edit to edit it.\n</p>\n      </dd>\n    </dl></div>\n</div>\n    <div class="clear"></div>\n    <div id="footer-brasil" class="footer-logos"></div>\n</div>\n<div id="extra-footer">\n    <p>Desenvolvido com o CMS de c\xc3\xb3digo aberto <a href="http://plone.org">Plone</a></p>\n</div>\n\n<!-- /Footer-->\n\n    \n    \n    <script defer src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>\n</div></body></html>\n'
```

Após plone.app.contenttypes >= 1.1.1.

https://travis-ci.org/plonegovbr/brasil.gov.portal/jobs/251299057

**Comment by idgserpro** [comment]
Feito em https://github.com/plonegovbr/brasil.gov.portal/pull/367.
