### ISSUE TITLE
Enquete não exibe resultado para usuário autenticado

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.portal#428]
Após votar em uma enquete com um usuário autenticado, não é exibido o resultado parcial. A tela fica como se o usuário não tivesse votado.

**Comment by hvelarde** [comment]
@idgserpro isso acontece no collective.polls isolado? conseguem criar um teste de RF para demostrar o erro?

**Comment by idgserpro** [comment]
Não consegui subir a instância do collective.poll após rodar o buildout dele. Então, não testei o collective.poll isolado.

**Comment by hvelarde** [comment]
tem que testar lá pois isso vai indicar melhor onde fica o problema; qual foi o erro?

**Comment by idgserpro** [comment]
Dá esse erro:

```bash
$ ./bin/instance fg
2017-12-12 19:05:32 INFO ZServer HTTP server started at Tue Dec 12 19:05:32 2017
	Hostname: 0.0.0.0
	Port: 8080
2017-12-12 19:05:34 WARNING plone.behavior Specifying 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.
2017-12-12 19:05:35 INFO Plone OpenID system packages not installed, OpenID support not available
Traceback (most recent call last):
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 92, in prepare
    self.startZope()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/Startup/__init__.py", line 268, in startZope
    Zope2.startup()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 120, in startup
    load_zcml()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/user/cache-python/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 651, in file
    context.execute_actions()
  File "/home/user/cache-python/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 626, in execute_actions
    callable(*args, **kw)
  File "/home/user/cache-python/eggs/AccessControl-3.0.11-py2.7-linux-x86_64.egg/AccessControl/security.py", line 165, in protectClass
    permission = getUtility(IPermission, name=permission_id)
  File "/home/user/cache-python/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 169, in getUtility
    raise ComponentLookupError(interface, name)
zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.AddPortalContent')
  in:
  File "/home/user/cache-python/eggs/plone.app.content-2.1.7-py2.7.egg/plone/app/content/browser/configure.zcml", line 7.4-12.10
      <browser:view
          for="Products.CMFCore.interfaces.IFolderish"
          name="+"
          class=".adding.CMFAdding"
          permission="cmf.AddPortalContent"
          />

```

**Comment by hvelarde** [comment]
parece com esse erro aqui: https://docs.plone.org/manage/troubleshooting/exceptions.html#componentlookuperror-cmf-manageportal

**Comment by hvelarde** [comment]
se o problema continuar, a issue deve ser aberta upstream no collective.polls.
