### ISSUE TITLE
Problema no upgrade 10804 da tag 2.0a1

### ISSUE THREAD

**Issue by makelli** [plonegovbr/brasil.gov.portal#448]
### Qual versão do produto você está usando e em qual sistema operacional (acesse /@@overview-controlpanel ou /prefs_install_products_form para obter essas informações)?

    Portal Padrão 2.0a1
    Plone 4.3.15 (4317)
    CMF 2.2.10
    Zope 2.13.26
    Python 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
    PIL 3.3.0 (Pillow)

### Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão? (IMPORTANTE: Pacotes apresentados [no manual de funcionalidades avançadas](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/manual-de-funcionalidades-avancadas-para-portais-plone_dez2014.pdf), mesmo que estejam no prefixo brasil.gov.\*, são considerados plugins adicionais). Caso sua resposta seja sim, forneça o nome e as versões utilizadas.
   

- [ X] Sim
Nome e versões dos plugins:
 plone.app.ldap-1.4.2
    collective.cover-1.6b5
    brasil.gov.portlets-1.0rc2
    brasil.gov.paginadestaque-1.2
    eea.facetednavigation-10.3     
    collective.carousel-1.7
    Products.PloneSurvey-1.4.10

- [ ] Não
- [ ] Não sei informar

### Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?

- [X ] Sim
- [ ] Não
- [ ] Não sei informar

### Se a resposta acima foi negativa, está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release/ e https://github.com/plonegovbr/brasil.gov.portal#requisitos?

- [ ] Sim
- [ ] Não
- [ ] Não sei informar

### Quais são os passos para reproduzir o problema?
Executar o passo a seguir:
Remove collective.nitf customizations      
 Remove customized view from types tool and set default view on objects using custom view. | (10803 → 10804)
-- | --

### A aplicação forneceu algum erro no console ou na interface? Cole nesse relato o erro completo.

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 1053, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 166, in doStep
  Module brasil.gov.portal.upgrades.v10804, line 42, in remove_nitf_customizations
AttributeError: 'tuple' object has no attribute 'remove'

**Comment by idgserpro** [comment]
Você está atualizando a partir de qual versão para a 2.0a1?

**Comment by makelli** [comment]
Da versão 1.5.1

**Comment by hvelarde** [comment]
o problema está [aqui](https://github.com/plonegovbr/brasil.gov.portal/blob/2.0a2/src/brasil/gov/portal/upgrades/v10804/__init__.py#L40-L41):

```python
if custom_view in nitf.view_methods:
    nitf.view_methods.remove(custom_view)
```

`view_methods` é uma tupla e as tuplas são imutáveis.

por outro lado, por favor teste sempre usando a última versão disponível, neste caso, a 2.0a2.

**Comment by idgserpro** [comment]
Erro ocorre no `master` (sendo mais específico, 6260b06a5ec398fd0839bdcaa799cfebe1942963). Criei uma instância 1.5.1, atualizei para o master, tentei rodar o upgradeStep e ocorreu esse erro.

Ao comentar a linha problemática como você afirmou em https://github.com/plonegovbr/brasil.gov.portal/issues/448#issuecomment-358984286, o upgradeStep funciona mas o site todo quebra, ficando:

![selecao_092](https://user-images.githubusercontent.com/8203476/36759330-be0e1280-1bf5-11e8-9ba3-4620ac3879ff.png)

Com o seguinte traceback:

```
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.subrequest-1.8.1-py2.7.egg/plone/subrequest/__init__.py", line 144, in subrequest
    traversed = request.traverse(path)
  File "/home/user/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 508, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/home/user/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 332, in traverseName
    ob2 = namespaceLookup(ns, nm, ob, self)
  File "/home/user/.buildout/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/namespace.py", line 112, in namespaceLookup
    return traverser.traverse(name, ())
  File "/home/user/.buildout/eggs/plone.resource-1.2.1-py2.7.egg/plone/resource/traversal.py", line 27, in traverse
    raise NotFound
NotFound
2018-02-27 19:35:54 ERROR plone.app.theming Couldn't resolve /++theme++verde/rules.xml
2018-02-27 19:35:54 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.transformchain-1.2.1-py2.7.egg/plone/transformchain/transformer.py", line 49, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/transform.py", line 183, in transformIterable
    transform = self.setupTransform(runtrace=runtrace)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/transform.py", line 121, in setupTransform
    transform = compileThemeTransform(rules, absolutePrefix, readNetwork, parameterExpressions, runtrace=runtrace)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/utils.py", line 602, in compileThemeTransform
    runtrace=runtrace,
  File "/home/user/.buildout/eggs/diazo-1.1.3-py2.7.egg/diazo/compiler.py", line 113, in compile_theme
    read_network=read_network,
  File "/home/user/.buildout/eggs/diazo-1.1.3-py2.7.egg/diazo/rules.py", line 210, in process_rules
    rules_doc = etree.parse(rules, parser=rules_parser)
  File "lxml.etree.pyx", line 2957, in lxml.etree.parse (src/lxml/lxml.etree.c:56299)
  File "parser.pxi", line 1526, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:82331)
  File "parser.pxi", line 1555, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:82624)
  File "parser.pxi", line 1455, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:81663)
  File "parser.pxi", line 1002, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:78623)
  File "parser.pxi", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)
  File "parser.pxi", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)
  File "parser.pxi", line 588, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74760)
IOError: Error reading file '/++theme++verde/rules.xml': failed to load external entity "/++theme++verde/rules.xml"
2018-02-27 19:35:55 ERROR plone.subrequest Error handling subrequest to /++theme++verde/rules.xml
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.subrequest-1.8.1-py2.7.egg/plone/subrequest/__init__.py", line 144, in subrequest
    traversed = request.traverse(path)
  File "/home/user/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 508, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/home/user/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 332, in traverseName
    ob2 = namespaceLookup(ns, nm, ob, self)
  File "/home/user/.buildout/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/namespace.py", line 112, in namespaceLookup
    return traverser.traverse(name, ())
  File "/home/user/.buildout/eggs/plone.resource-1.2.1-py2.7.egg/plone/resource/traversal.py", line 27, in traverse
    raise NotFound
NotFound
2018-02-27 19:35:55 ERROR plone.app.theming Couldn't resolve /++theme++verde/rules.xml
2018-02-27 19:35:55 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/plone.transformchain-1.2.1-py2.7.egg/plone/transformchain/transformer.py", line 49, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/transform.py", line 183, in transformIterable
    transform = self.setupTransform(runtrace=runtrace)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/transform.py", line 121, in setupTransform
    transform = compileThemeTransform(rules, absolutePrefix, readNetwork, parameterExpressions, runtrace=runtrace)
  File "/home/user/.buildout/eggs/plone.app.theming-1.1.8-py2.7.egg/plone/app/theming/utils.py", line 602, in compileThemeTransform
    runtrace=runtrace,
  File "/home/user/.buildout/eggs/diazo-1.1.3-py2.7.egg/diazo/compiler.py", line 113, in compile_theme
    read_network=read_network,
  File "/home/user/.buildout/eggs/diazo-1.1.3-py2.7.egg/diazo/rules.py", line 210, in process_rules
    rules_doc = etree.parse(rules, parser=rules_parser)
  File "lxml.etree.pyx", line 2957, in lxml.etree.parse (src/lxml/lxml.etree.c:56299)
  File "parser.pxi", line 1526, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:82331)
  File "parser.pxi", line 1555, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:82624)
  File "parser.pxi", line 1455, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:81663)
  File "parser.pxi", line 1002, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:78623)
  File "parser.pxi", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)
  File "parser.pxi", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)
  File "parser.pxi", line 588, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74760)
IOError: Error reading file '/++theme++verde/rules.xml': failed to load external entity "/++theme++verde/rules.xml"

```

**Comment by hvelarde** [comment]
o problema é o tema usado: o tema verde não existe ainda, só só o padrão; testa por favor mudando o tema de forma manual e abre uma outra issue para isso.

**Comment by idgserpro** [comment]
Vão existir os temas com as mesmas cores/nomes que os atuais?

**Comment by hvelarde** [comment]
eu acho que sim, mas o @agnogueira deve ter mais detalhes.

**Comment by agnogueira** [comment]
@idgserpro a ideia inicial é que tenha sim, mas vamos precisar primeiro finalizar um tema para depois derivar os demais

**Comment by idgserpro** [comment]
Sim, a idéia é evitar esse tipo de erro como o de cima, porque o nome do tema não existe. Pra evitar esse erro os temas precisarão ter o mesmo nome.

Mas isso não é o escopo dessa issue, apenas aproveitei o gancho. Obrigado.
