### ISSUE TITLE
Erro ao acessar a tela de login

### ISSUE THREAD

**Issue by agnogueira** [plonegovbr/brasil.gov.portal#515]
Ao acessar a tela de login de um portal com o IDG ocorre um erro.

No registro de erros do Plone temos a seguinte mensagem:

```pytb
2018-08-28T15:35:32 ERROR plone.app.viewletmanager Error while rendering viewlet-manager=plone.portaltop, viewlet=plone.header
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/plone.app.viewletmanager-2.0.11-py2.7.egg/plone/app/viewletmanager/manager.py", line 112, in render
    html.append(viewlet.render())
  File "/opt/plone/buildout/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/opt/plone/buildout/eggs/Zope2-2.13.27-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/opt/plone/buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/opt/plone/buildout/eggs/five.pt-2.2.5-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/opt/plone/buildout/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/opt/plone/buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/opt/plone/buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/opt/plone/buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "/opt/plone/buildout/var/chameleon-cache/802533b237e3d3d5aae8a83165fad16e.py", line 100, in render
    __cache_139982278664976 = _render_content_provider(econtext, __cache_139982278664976)
  File "/opt/plone/buildout/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/expressions.py", line 71, in render_content_provider
    cp.update()
  File "/opt/plone/buildout/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 112, in update
    self._updateViewlets()
  File "/opt/plone/buildout/eggs/zope.viewlet-3.7.2-py2.7.egg/zope/viewlet/manager.py", line 118, in _updateViewlets
    viewlet.update()
  File "/opt/plone/buildout/src/brasil.gov.portal/src/brasil/gov/portal/browser/viewlets/services.py", line 16, in update
    self.portal_services = portal_services_view.actions('portal_services')
  File "/opt/plone/buildout/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/opt/plone/buildout/eggs/plone.app.layout-2.3.17-py2.7.egg/plone/app/layout/globals/context.py", line 237, in actions
    max=max,
  File "/opt/plone/buildout/eggs/Products.CMFPlone-4.3.17-py2.7.egg/Products/CMFPlone/ActionsTool.py", line 56, in listActionInfos
    actions = [ActionInfo(action, ec) for action in actions]
  File "/opt/plone/buildout/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/ActionInformation.py", line 190, in __init__
    (lazy_map, lazy_keys) = action.getInfoData()
  File "/opt/plone/buildout/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/ActionInformation.py", line 156, in getInfoData
    val = Message(val, self.i18n_domain)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

 - Stream:     Link obrigatório para o topo do site
                           ^
 - Expression: "provider:plone.portalheader"
 - Filename:   ... .17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt
 - Location:   (line 2: col 32)
 - Source:     ... :replace="structure provider:plone.portalheader" />
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f77b20a1e10>
               views: <ViewMapper - at 0x7f77c7b05b50>
               modules: <instance - at 0x7f77c85cf1b8>
               args: <tuple - at 0x7f77cfdc3050>
               here: <ImplicitAcquisitionWrapper IDG at 0x7f77b2eb28c0>
               user: <ImplicitAcquisitionWrapper - at 0x7f77b2c91820>
               nothing: <NoneType - at 0x55fda71a1560>
               container: <ImplicitAcquisitionWrapper IDG at 0x7f77b2eb28c0>
               request: <instance - at 0x7f77c7ce16c8>
               wrapped_repeat: <SafeMapping - at 0x7f77b0c4d100>
               traverse_subpath: <list - at 0x7f77b0984758>
               default: <object - at 0x7f77cfcde560>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper IDG at 0x7f77b2eb28c0>
               view: <SimpleViewletClass from /opt/plone/buildout/eggs/plone.app.layout-2.3.17-py2.7.egg/plone/app/layout/viewlets/portal_header.pt plone.header at 0x7f77c7b05990>
               translate: <function translate at 0x7f77c7b181b8>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f77b2dec820>
               options: {...} (0)
               target_language: pt_BR
```

**Comment by hvelarde** [comment]
o workaround por enquanto é trocar o encoding do Python usado no deploy para `utf-8`.
