### ISSUE TITLE
Falha na instalação do brasil.gov.temas ao rodar buildout

### ISSUE THREAD

**Issue by miraidensetsu** [plonegovbr/brasil.gov.portal#548]
Como resolvo isso?

**Qual versão do produto você está usando e em qual sistema operacional?**

Tentando instalar a versão 2.1rc1 sobre a versão 2.0b3

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**

Não.

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**

Sim.

**Quais são os passos para reproduzir o problema?**

Basicamente estou tentando rodar o buildout.

**Qual é o retorno esperado? O que você vê ao contrário do esperado?**

O portal não instala o brasil.gov.temas e o portal simplesmente falha em iniciar depois.

**A aplicação forneceu algum erro no console ou na interface?**

Updating staticresources-agenda.
staticresources-agenda: Install debug-brasilgovagenda
staticresources-agenda: Install test-brasilgovagenda
staticresources-agenda: Install watch-brasilgovagenda
staticresources-agenda: Install build-brasilgovagenda
staticresources-agenda: Install env-brasilgovagenda
yarn install v1.9.4
[1/4] Resolving packages...
warning sc-recipe-staticresources > sinon > nise > text-encoding@0.6.4: no longer maintained
warning sc-recipe-staticresources > hard-source-webpack-plugin > jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error html-webpack-plugin@3.2.0: The engine "node" is incompatible with this module. Expected version ">=6.9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> brasilgovagenda@0.0.1 build /home/miraidensetsu/portal-novo/src/brasil.gov.agenda/webpack
> webpack -p

/home/miraidensetsu/portal-novo/src/brasil.gov.agenda/webpack/webpack.config.js:22
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/miraidensetsu/portal-novo/src/brasil.gov.agenda/webpack/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/miraidensetsu/portal-novo/src/brasil.gov.agenda/webpack/node_modules/webpack/bin/convert-argv.js:104:17
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brasilgovagenda@0.0.1 build: `webpack -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brasilgovagenda@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-19T22_33_18_920Z-debug.log
Updating staticresources-temas.
staticresources-temas: Install debug-brasilgovtemas
staticresources-temas: Install test-brasilgovtemas
staticresources-temas: Install watch-brasilgovtemas
staticresources-temas: Install build-brasilgovtemas
staticresources-temas: Install env-brasilgovtemas
yarn install v1.9.4
[1/4] Resolving packages...
warning sc-recipe-staticresources > hard-source-webpack-plugin > jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning sc-recipe-staticresources > sinon > nise > text-encoding@0.6.4: no longer maintained
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
error hard-source-webpack-plugin@0.12.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> brasilgovtemas@2.0.2 build /home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack
> webpack -p

/home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack/webpack.config.js:28
      );
      ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack/node_modules/webpack/bin/convert-argv.js:104:17
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brasilgovtemas@2.0.2 build: `webpack -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brasilgovtemas@2.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-19T22_33_26_032Z-debug.log

O conteúdo do log:

0 info it worked if it ends with ok
1 verbose cli [ '/home/miraidensetsu/portal-novo/parts/buildout-node/node-v6.6.0-linux-x64/bin/node',
1 verbose cli   '/home/miraidensetsu/portal-novo/parts/webpack/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.0
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle brasilgovtemas@2.0.2~prebuild: brasilgovtemas@2.0.2
6 info lifecycle brasilgovtemas@2.0.2~build: brasilgovtemas@2.0.2
7 verbose lifecycle brasilgovtemas@2.0.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle brasilgovtemas@2.0.2~build: PATH: /home/miraidensetsu/portal-novo/parts/webpack/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack/node_modules/.bin:/home/miraidensetsu/portal-novo/parts/webpack/bin:/home/miraidensetsu/portal-novo/parts/buildout-node/node-v6.6.0-linux-x64/bin:/home/miraidensetsu/portal-novo/parts/webpack/bin:/home/miraidensetsu/portal-novo/bin:/usr/lib64/qt-3.3/bin:/home/miraidensetsu/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/miraidensetsu/.local/bin:/home/miraidensetsu/bin
9 verbose lifecycle brasilgovtemas@2.0.2~build: CWD: /home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack
10 silly lifecycle brasilgovtemas@2.0.2~build: Args: [ '-c', 'webpack -p' ]
11 silly lifecycle brasilgovtemas@2.0.2~build: Returned: code: 1  signal: null
12 info lifecycle brasilgovtemas@2.0.2~build: Failed to exec build script
13 verbose stack Error: brasilgovtemas@2.0.2 build: `webpack -p`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/miraidensetsu/portal-novo/parts/webpack/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/miraidensetsu/portal-novo/parts/webpack/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid brasilgovtemas@2.0.2
15 verbose cwd /home/miraidensetsu/portal-novo/src/brasil.gov.temas/webpack
16 verbose Linux 3.10.0-862.11.6.el7.x86_64
17 verbose argv "/home/miraidensetsu/portal-novo/parts/buildout-node/node-v6.6.0-linux-x64/bin/node" "/home/miraidensetsu/portal-novo/parts/webpack/bin/npm" "run" "build"
18 verbose node v6.6.0
19 verbose npm  v6.4.0
20 error code ELIFECYCLE
21 error errno 1
22 error brasilgovtemas@2.0.2 build: `webpack -p`
22 error Exit status 1
23 error Failed at the brasilgovtemas@2.0.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hvelarde** [comment]
o problema é a versão de node instalada; apaga a pasta `parts/buildout-node` e roda o buildout de novo, por favor.

precisamos achar um jeito de isso acontecer automaticamente.
