### ISSUE TITLE
AttributeError após atualizar de v2.1rc1 para v2.1rc2

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#560]
**Qual versão do produto você está usando e em qual sistema operacional?**

Portal Padrão 2.1rc2
Plone 4.3.18 (4320)
CMF 2.2.10
Zope 2.13.28
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
PIL 3.3.3 (Pillow)

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**

Não.

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**

Sim.

**Está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release e https://github.com/plonegovbr/brasil.gov.portal#requisitos?**

Sim.

**A aplicação forneceu algum erro no console ou na interface?**

```pytb
2018-11-26T14:32:55 ERROR plone.subrequest Error handling subrequest to http://www.exemplo.gov.br/pagina-inicial/@@collective.cover.list/b6
3c86a1-4d63-434b-95ad-0962bfefef42
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/plone.subrequest-1.8.5-py2.7.egg/plone/subrequest/__init__.py", line 156, in subrequest
    bind=1
  File "/opt/plone/buildout/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/mapply.py", line 78, in mapply
    else: return object(*args)
  File "/opt/plone/buildout/eggs/plone.tiles-2.1-py2.7.egg/plone/tiles/esi.py", line 87, in __call__
    return self.index(*args, **kwargs)
  File "/opt/plone/buildout/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/opt/plone/buildout/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/opt/plone/buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/opt/plone/buildout/eggs/five.pt-2.2.5-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/opt/plone/buildout/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/opt/plone/buildout/eggs/Chameleon-2.25-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/opt/plone/buildout/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/opt/plone/buildout/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "/opt/plone/buildout/var/chameleon-cache/39b122d773e4eb1ae5b62830654fb0cb.py", line 114, in render
  File "/opt/plone/buildout/eggs/five.pt-2.2.5-py2.7.egg/five/pt/expressions.py", line 161, in __call__
    return base()
  File "/opt/plone/buildout/eggs/collective.cover-1.8b2-py2.7.egg/collective/cover/tiles/list.py", line 141, in is_empty
    return self.results() == []
  File "/opt/plone/buildout/eggs/collective.cover-1.8b2-py2.7.egg/collective/cover/tiles/list.py", line 120, in results
    ordered_uuids = [(k, v) for k, v in uuids.items()]
AttributeError: 'list' object has no attribute 'items'

 - Expression: "view/is_empty"
 - Filename:   ... 1.8b2-py2.7.egg/collective/cover/tiles/templates/list.pt
 - Location:   (line 7: col 27)
 - Source:     <body tal:define="is_empty view/is_empty">
                                          ^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f0c4b16ead0>
               views: <ViewMapper - at 0x7f0c4b16e790>
               modules: <instance - at 0x7f0c587dc098>
               args: <tuple - at 0x7f0c601d4050>
               here: <ImplicitAcquisitionWrapper pagina-inicial at 0x7f0c4a410d70>
               user: <ImplicitAcquisitionWrapper - at 0x7f0c4a410f50>
               nothing: <NoneType - at 0x55d0439db560>
               container: <ImplicitAcquisitionWrapper pagina-inicial at 0x7f0c4a410d70>
               request: <instance - at 0x7f0c4123cfc8>
               wrapped_repeat: <SafeMapping - at 0x7f0c411f40a8>
               traverse_subpath: <list - at 0x7f0c49efd6c8>
               default: <object - at 0x7f0c600ef580>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper pagina-inicial at 0x7f0c4a410d70>
               view: <ListTile collective.cover.list at 0x7f0c4b16ec90>
               translate: <function translate at 0x7f0c41e64230>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f0c49bcbaa0>
               options: {...} (0)
               target_language: pt_BR
```

**Comment by rodfersou** [comment]
Só precisa rodar novamente o upgrade step **Migrate data from tiles that have been removed**.

**Comment by hvelarde** [comment]
o upgrade step deve rodar automaticamente; precisamos alterar o código para isso acontecer.

**Comment by hvelarde** [comment]
@idgserpro não estamos conseguindo entender se o problema só aconteceu no site que atualizamos; eu sei que outros sites foram atualizados sem problemas.

gostaria vocês dar um feedback quando conseguirem usar esta versão para saber se podemos considerar fechado ou não.
