### ISSUE TITLE
Erro ao rodar webpack

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.portal#563]
```
Webpack is watching the files…

[hardsource:cef03a5e] Using 2 MB of disk space.
[hardsource:cef03a5e] Tracking node dependencies with: yarn.lock.
[hardsource:cef03a5e] Reading from cache cef03a5e...
Hash: e2476f86af9344d1e604
Version: webpack 3.12.0
Time: 1502ms
                     Asset       Size  Chunks             Chunk Names
           img/preview.png  281 bytes          [emitted]  
brasilgovportal-f357bf7.js     159 kB       0  [emitted]  main
              resources.pt  131 bytes          [emitted]  
   [0] multi ./app/img/preview.png ./app/brasilgovportal.scss ./app/brasilgovportal.js 52 bytes {0} [built]
   [2] ./app/brasilgovportal.scss 1.3 kB {0} [built] [failed] [1 error]
    + 7 hidden modules

ERROR in ./app/brasilgovportal.scss
Module build failed: ModuleBuildError: Module build failed: 
@import 'scss/sprite';
^
      File to import not found or unreadable: scss/sprite.
      in /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/app/brasilgovportal.scss (line 1, column 1)
    at runLoaders (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/sass-loader/lib/loader.js:52:13)
    at Object.done [as callback] (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/neo-async/async.js:8077:18)
    at options.error (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./app/img/preview.png ./app/brasilgovportal.scss ./app/brasilgovportal.js

ERROR in ./app/brasilgovportal.scss
Module build failed: ModuleBuildError: Module build failed: 
@import 'scss/sprite';
^
      File to import not found or unreadable: scss/sprite.
      in /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/app/brasilgovportal.scss (line 1, column 1)
    at runLoaders (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/sass-loader/lib/loader.js:52:13)
    at Object.done [as callback] (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/neo-async/async.js:8077:18)
    at options.error (/home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/node_modules/node-sass/lib/index.js:294:32)
 @ ./app/brasilgovportal.scss
 @ multi ./app/img/preview.png ./app/brasilgovportal.scss ./app/brasilgovportal.js
Child html-webpack-plugin for "resources.pt":
     1 asset
       4 modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!app/brasilgovportal.scss:
       [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/brasilgovportal.scss 254 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/brasilgovportal.scss
    Module build failed: 
    @import 'scss/sprite';
    ^
          File to import not found or unreadable: scss/sprite.
          in /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/app/brasilgovportal.scss (line 1, column 1)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js!app/brasilgovportal.scss:
       [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/brasilgovportal.scss 254 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/brasilgovportal.scss
    Module build failed: 
    @import 'scss/sprite';
    ^
          File to import not found or unreadable: scss/sprite.
          in /home/rodfersou/.projects/portal.buildout/src/brasil.gov.portal/webpack/app/brasilgovportal.scss (line 1, column 1)
```

**Qual versão do produto você está usando e em qual sistema operacional?**

**Possui plugins adicionados além dos definidos numa instalação padrão do Portal Padrão?**

**Está utilizando o buildout padrão como o usado em https://github.com/plonegovbr/portal.buildout?**

**Está utilizando o arquivo de versões de pinagens das dependências como definido em https://github.com/plonegovbr/portalpadrao.release e https://github.com/plonegovbr/brasil.gov.portal#requisitos?**

**Quais são os passos para reproduzir o problema?**

**Qual é o retorno esperado? O que você vê ao contrário do esperado?**

**A aplicação forneceu algum erro no console ou na interface?**

**Por favor forneça informações adicionais que possam complementar o seu relato:**

**Comment by rodfersou** [comment]
Corrigido em https://github.com/plonegovbr/brasil.gov.portal/pull/562
